name: iOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-ios:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu
          cache: gradle

      - name: Set up Ruby
        uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939 # v1.152.0
        with:
          bundler-cache: true

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      - uses: hendrikmuhs/ccache-action@v1
        name: Xcode Compile Cache
        with:
          key: ${{ runner.os }}-v2 # makes a unique key w/related restore key internally
          max-size: 1500M

      - name: Run xcodebuild
        run: |
          cd sample/ios
          xcodebuild -scheme peekaboo -sdk iphoneSimulator
